import { HttpException, HttpStatus } from "@nestjs/common";

export class AppException extends HttpException {
  constructor(
    public readonly code: string,
    message: string,
    status: HttpStatus,
  ) {
    super({ code, message }, status);
  }

  get httpStatus(): HttpStatus {
    return this.getStatus() as HttpStatus;
  }

  static readonly errorCodes = {
    cart: {
      PRODUCT_NOT_FOUND: "CART_001",
      PRODUCT_ALREADY_IN_CART: "CART_002",
      ANONYMOUS_CUSTOMER_NOT_FOUND: "CART_003",
      CART_NOT_FOUND: "CART_004",
      PRODUCT_NOT_FOUND_IN_CART: "CART_005",
      PRODUCT_OUT_OF_STOCK: "CART_006",
      CUSTOMER_NOT_FOUND: "CART_007",
      PRODUCT_INACTIVE: "CART_008",
      INVALID_SESSION: "CART_009",
      COUPON_NOT_FOUND: "CART_010",
      COUPON_UNAVAILABLE: "CART_011",
      COUPON_MIN_ORDER_NOT_MET: "CART_012",
      COUPON_USAGE_LIMIT_REACHED: "CART_013",
      COUPON_ALREADY_USED: "CART_014",
      COUPON_REQUIRES_AUTH: "CART_015",
      COUPON_NOT_ASSIGNED: "CART_016",
    },
    auth: {
      ANONYMOUS_CUSTOMER_NOT_FOUND: "AUTH_001",
      INVALID_VERIFICATION_CODE: "AUTH_002",
      INVALID_REFRESH_TOKEN: "AUTH_004",
      CUSTOMER_NOT_FOUND: "AUTH_005",
      INVALID_TOKEN_IN_DECORATOR: "AUTH_006",
      RATE_LIMIT_EXCEEDED: "AUTH_007",
    },
    me: {
      CUSTOMER_NOT_FOUND: "ME_001",
      NO_FIELDS_TO_UPDATE: "ME_002",
      ADDRESS_ALREADY_EXISTS: "ME_003",
      ADDRESS_NOT_FOUND: "ME_004",
      ALREADY_INITIALIZED: "ME_005",
      CANNOT_REMOVE_MAIN_ADDRESS: "ME_006",
      LIMITED_NUMBER_OF_ADDRESSES: "ME_007",
      ADDRESS_ALREADY_MAIN: "ME_008",
      CANNOT_DELETE_WITH_ACTIVE_ORDER: "ME_009",
    },
    order: {
      CUSTOMER_NOT_FOUND: "ORDER_001",
      CUSTOMER_NOT_INITIALIZED: "ORDER_002",
      CART_EMPTY: "ORDER_003",
      ONGOING_ORDER: "ORDER_004",
      PRODUCTS_OUT_OF_STOCK: "ORDER_005",
      PRODUCT_INACTIVE: "ORDER_006",
      ORDER_NOT_FOUND: "ORDER_007",
      ORDER_NOT_CANCELLABLE: "ORDER_008",
      NO_MAIN_ADDRESS: "ORDER_009",
      INACTIVE_CUSTOMER: "ORDER_010",
      BELOW_MIN_ORDER_VALUE: "ORDER_011",
      OUTSIDE_BUSINESS_HOURS: "ORDER_012",
      ON_BREAK: "ORDER_013",
      COUPON_UNAVAILABLE: "ORDER_014",
      COUPON_MIN_ORDER_NOT_MET: "ORDER_015",
      COUPON_USAGE_LIMIT_REACHED: "ORDER_016",
      COUPON_ALREADY_USED: "ORDER_017",
    },
    products: {
      INVALID_SESSION: "PRODUCTS_001",
    },
    adminProducts: {
      PRODUCT_NOT_FOUND: "ADMIN_PRODUCTS_002",
      INVALID_CATEGORY: "ADMIN_PRODUCTS_003",
      CATEGORY_INACTIVE: "ADMIN_PRODUCTS_004",
      INVALID_PRODUCTS_ORDER: "ADMIN_PRODUCTS_005",
    },
    adminCategories: {
      CATEGORY_NOT_FOUND: "ADMIN_CATEGORIES_001",
      CATEGORY_HAS_PRODUCTS: "ADMIN_CATEGORIES_002",
      CATEGORY_ALREADY_EXISTS: "ADMIN_CATEGORIES_003",
      INVALID_CATEGORIES_ORDER: "ADMIN_CATEGORIES_004",
    },
    adminCustomers: {
      CUSTOMER_NOT_FOUND: "ADMIN_CUSTOMERS_001",
      CUSTOMER_HAS_ORDERS: "ADMIN_CUSTOMERS_002",
    },
    adminOrders: {
      ORDER_NOT_FOUND: "ADMIN_ORDERS_001",
      ORDER_ALREADY_FINALIZED: "ADMIN_ORDERS_002",
      ORDER_INVALID_STATUS_TRANSITION: "ADMIN_ORDERS_003",
    },
    adminInventory: {
      INSUFFICIENT_STOCK: "ADMIN_INVENTORY_001",
      PRODUCT_NOT_FOUND: "ADMIN_INVENTORY_002",
      DUPLICATE_PRODUCT: "ADMIN_INVENTORY_003",
    },
    adminCoupons: {
      COUPON_NOT_FOUND: "ADMIN_COUPONS_001",
      COUPON_ALREADY_EXISTS: "ADMIN_COUPONS_002",
      COUPON_START_NOT_EDITABLE: "ADMIN_COUPONS_004",
      INVALID_USAGE_LIMIT: "ADMIN_COUPONS_005",
    },
  };

  static readonly HttpStatus = HttpStatus;
}
